
project_id = "jpjuvzpqfirymtjwnier"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[analytics]
enabled = false
port = 54328

[vector]
enabled = false
port = 54329

# Configuration pour les fonctions avec vérification JWT désactivée pour le debug
[functions.completer-profil]
verify_jwt = false

[functions.create-test-data]
verify_jwt = false
